universe                = docker
docker_image            = tensorflow/tensorflow:latest-gpu
executable              = execute.sh
arguments               = test_condor.py
output                  = condor_logs/test.$(ClusterId).$(ProcId).out
error                   = condor_logs/test.$(ClusterId).$(ProcId).err
log                     = condor_logs/test.$(ClusterId).log

transfer_input_files    = ., /home/hlcv_team017/HLCV2023/, /home/hlcv_team017/miniconda3/envs/hlcv-ss23/bin/python
should_transfer_files   = YES

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_CPUs = 6
request_memory = 5G
requirements = UidDomain == "cs.uni-saarland.de"
getenv = HOME
queue 1
